### ISSUE TITLE
Card (7d) still misaligned in Vertical4 sprite.png

### ISSUE THREAD

**Issue by kheremos** [saulspatz/SVGCards#2]
I noticed you had a PR where you updated the alignment of this problematic card.  Unfortunately for me, I picked [the image where it has not been corrected](https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical4/pngs/sprite.png).  I'm not sure if you're still keeping the repo up-to-date, and unfortunately I can't fix it and submit a PR because I'm without a dev machine at the moment...

Thanks for your work!  Similar offerings had viral licenses...

https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical4/pngs/sprite.png

**Comment by saulspatz** [comment]
I haven't looked at this, or used inkscape, in a long time, but I'll be
happy to try to fix it.  It may take me a little while.  If it hasn't been
fixed in 7 days from today, please remind me.

**Comment by kheremos** [comment]
Thanks!  I was just looking for a public domain spritesheet to use as a placeholder for a project I'm working on..
So, the following two have the 7d misalignment issue:

https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical2/gifs/sprite.gif
https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical2/pngs/sprite.png
https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical4/gifs/sprite.gif
https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical4/pngs/sprite.png

But I can use [[this one](https://github.com/saulspatz/SVGCards/blob/master/Decks/Horizontal4/pngs/sprite.png)], so no rush.  Both of the Horizontal options seem to be rendered correctly.

Also, have you considered red hearts, green clubs, blue diamonds and black spades?  I believe that's actually an accessibility setting for a variety of poker applications (pokerstars among them).  Sorry for such an annoying request, I really should set up a better environment for myself...

**Comment by kheremos** [comment]
And actually, looking closer at https://raw.githubusercontent.com/saulspatz/SVGCards/master/Decks/Vertical4/svgs/sprite.svg it looks like the 7d needs to be moved vertically by a pixel or two.

**Comment by saulspatz** [comment]
I did this for myself, because I couldn't find a deck that I liked for my
own games.  Once I got something I liked,  I decided to share it, and I
haven't looked at inkscape since.  So, I don't know how much work changing
the colors entails.  I'm a retiree, with lots of time on my hands though,
so I'm interested in any project.  I'll look into it.

**Comment by saulspatz** [comment]
I agree with you on the vertical4 sprite.

**Comment by kheremos** [comment]
And I hope this ticket isn't bothersome for you.  I really appreciate your work.  

I don't know how much you enjoy coding or poker analysis, but might I recommend [this cool article by Keith Rule](https://www.codeproject.com/Articles/12279/Fast-Texas-Holdem-Hand-Evaluation-and-Analysis)?

**Comment by saulspatz** [comment]
Thanks.  I enjoy coding, but I'm not interested in poker.  I looked at the
project, and I see that I have a python script for automatically
changing the suit colors, so I think I can promise to do that, at least for
the individual cards.  Not sure about the sprite sheets yet.  If I remember
correctly, I had a lot of trouble making them in the first place, and
things get harder for me with each passing year.  I'll certainly give it a
try if the color change works as expected.

**Comment by saulspatz** [comment]
Hi,

I think I've got everything we talked about done.  I'm not terribly happy
with the coloring job on the accessible decks, but I did my best.

Please let me know of any problems or omissions.

Saul

**Comment by kheremos** [comment]
Looks great.  Will import the green PNG into my app and see if everything lines up.  Thanks!

**Comment by luiscastro193** [comment]
These are great, thanks for the good work. I made a [little memory game](https://luiscastro193.github.io/memory/) with these cards. However, the 7 of diamonds I'm using is still misaligned:

https://github.com/saulspatz/SVGCards/blob/master/Decks/Vertical2/svgs/diamond7.svg

**Comment by saulspatz** [comment]
Do you mean that the rectangle containing the seven diamond pips isn't
centered correctly?

**Comment by luiscastro193** [comment]
Yes, exactly

**Comment by saulspatz** [comment]
Thanks.  I'll try to fix it.  I may not get to it until sometime next week.

**Comment by luiscastro193** [comment]
Great, thanks!

**Comment by saulspatz** [comment]
Should be fixed for all decks now, for sprites, and individual cards, both SVGs and PNGs.  Let me know if I've missed anything, please.

**Comment by luiscastro193** [comment]
It's perfect now, thanks a lot!

**Comment by saulspatz** [comment]
You;ew welcome.  Thanks again for pointing out the problem.
